name: Veracode DAST

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  dast:
    runs-on: ubuntu-latest

    env:
      VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
      VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
      VERACODE_TARGET_ID: ${{ secrets.VERACODE_TARGET_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Veracode CLI
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          echo "$PWD" >> $GITHUB_PATH

      - name: Verify CLI
        run: veracode version

      ###########################################################
      # Start Scan
      ###########################################################

      - name: Start DAST Scan
        id: start_scan
        shell: bash
        continue-on-error: true
        run: |
          set -e

          veracode dynamic scan \
            --webhook "$VERACODE_TARGET_ID" \
            | tee scan.log

          RUN_ID=$(awk '/Analysis run id:/ {print $NF}' scan.log)

          if [ -z "$RUN_ID" ]; then
            echo "Unable to retrieve Analysis Run ID"
            exit 1
          fi

          echo "Analysis Run ID = $RUN_ID"

          echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"

      ###########################################################
      # Download JSON Result
      ###########################################################

      - name: Download JSON Report
        continue-on-error: true
        run: |
          veracode dynamic results \
            --webhook "$VERACODE_TARGET_ID" \
            --analysis-run-id "${{ steps.start_scan.outputs.run_id }}" \
            --format json \
            --output results.json

      ###########################################################
      # Download PDF Report
      ###########################################################

      - name: Download PDF Report
        continue-on-error: true
        run: |
          veracode dynamic results \
            --webhook "$VERACODE_TARGET_ID" \
            --analysis-run-id "${{ steps.start_scan.outputs.run_id }}" \
            --format pdf \
            --output report.pdf

      ###########################################################
      # Upload Artifact
      ###########################################################

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: veracode-dast
          path: |
            scan.log
            results.json
            report.pdf